name: CICD for Node.js Backend

on:
  push:
    branches:
      - master

jobs:
  build :
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install


  # Deploy Job
  deploy:
   
    name: Deploy to Server
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Deploy via SSH
        run: |
          scp -r . user@your-server.com:/path/to/app
        env:
          SSH_PRIVATE_KEY: ${{ secrets.myToken2025}}