name: CICD for Node.js Backend

on:
  push:
    branches:
      - master

jobs:
  build :
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install


  # Deploy Job
  deploy:
          
    needs: build
    
    runs-on: ubuntu-latest
    steps:
      - name: Debug token presence
        run: |
          if [ -z "${{ secrets.myToken2025 }}" ]; then
            echo "Token is empty or not found!"
            exit 1
          else
            echo "Token is present."
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}} #this is the key of the access token
